version: "3.9"
services:

  shapeloader:
    container_name: SHAPELOADER_DEV
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 2345:2345
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/workspaces/shape-sql-loader
    env_file:
      - .devcontainer/devcontainer.env
    working_dir: /workspaces/shape-sql-loader
    tty: true
    entrypoint: ["bash"]
    # dlv entrypoint to auto setup debugging server
    # entrypoint: ['/go/bin/dlv', '--listen=: 2345', '--headless=true', '--api-version=2', 'exec', 'main.go']

  postgis:
    image: kartoza/postgis
    container_name: POSTGIS_SHAPELOADER_DEV
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASS=notPassword
      - TIMESCALEDB_TELEMETRY=off
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

