version: "3.9"
services:

  shapeloader:
    container_name: SHAPELOADER_DEV
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3031:3031
    volumes:
      - .:/workspaces/shape-sql-loader
    env_file:
      - .devcontainer/devcontainer.env
    working_dir: /workspaces/shape-sql-loader
    tty: true
    entrypoint: ["bash"]

  postgis:
    image: kartoza/postgis
    container_name: POSTGIS_SHAPELOADER_DEV
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASS=notPassword
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

