#!/bin/bash

directory="."
suffix="shp"
sqlCred="host=host.docker.internal port=25432 user=admin password=notPassword dbname=gis"

uploadShp () {
    list=$(find $directory -type f -name "*.$suffix")

    for file in $list
    do
        echo "Uploading $file"
        ogr2ogr -f "PostgreSQL" PG:"$sqlCred" $file -lco precision=NO
    done
}

uploadShp
