#!/bin/bash

while getopts d:s:c:t: flag
do
    case "$flag" in
        d) directory=${OPTARG};;
        s) sqlCred=${OPTARG};;
        c) schema=${OPTARG};;
        t) table=${OPTARG};;
    esac
done

suffix="shp"

uploadShp () {
    list=$(find $directory -type f -name "*.$suffix")
    for file in $list
    do
        echo "Uploading $file"
        # -update avoid creation a new datasource
        # -append merge matching layers
        ogr2ogr -append -update -f "PostgreSQL" PG:"$sqlCred" $file -nln $schema.$table
    done
}

uploadShp
