#!/bin/bash

while getopts d:s:c:t: flag
do
    case "$flag" in
        f) file=${OPTARG};;
        s) sqlCred=${OPTARG};;
        c) schema=${OPTARG};;
        t) table=${OPTARG};;
    esac
done

uploadShp () {
    echo "Uploading $file"
    # -update avoid creating a new datasource
    # -append merges matching layers
    ogr2ogr -append -update -progress -f "PostgreSQL" PG:"$sqlCred" $file -nln $schema.$table
}

uploadShp
