#!/bin/bash

# debugging
# set -x

# Upload multiple shape file using "upload" --mode
while getopts d:s:x: flag
do
    case "$flag" in
        d) directory=${OPTARG};;
        s) sqlCred=${OPTARG};;
        x) xlsPath=${OPTARG};;
    esac
done

suffix="shp"

upload() {
    list=$(find $directory -type f -name "*.$suffix" -print | sort )
    declare -i i=1
    len=$(find $directory -type f -name "*.$suffix" | wc -l)
    for file in $list
    do
        echo "Uploading $i/$len - $file"
        declare -a cmd=("go run . --mode upload --sqlConn \"$sqlCred\" --xlsPath $xlsPath --shpPath $file")
        eval $cmd
        i=$(($i+1))
    done
}

upload
